front:
  image: dydx/alpine-nginx-phpfpm
  ports:
    - "4011:80"
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/sites-enabled
  links:
    - mysql:mysql

mysql:
  image: dydx/alpine-mariadb
  ports:
    - "3318:3306"
  volumes:
    - ./database:/var/lib/mysql
